///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the iOS_WS_TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("86fe5850-ab94-44e4-9bb2-fb364318e80c")]
    public partial class iOS_WS_TestRepository : RepoGenBaseFolder
    {
        static iOS_WS_TestRepository instance = new iOS_WS_TestRepository();
        iOS_WS_TestRepositoryFolders.ComPentairPentairhomeAppFolder _compentairpentairhome;
        RepoItemInfo _productsupport_linkInfo;

        /// <summary>
        /// Gets the singleton class instance representing the iOS_WS_TestRepository element repository.
        /// </summary>
        [RepositoryFolder("86fe5850-ab94-44e4-9bb2-fb364318e80c")]
        public static iOS_WS_TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public iOS_WS_TestRepository() 
            : base("iOS_WS_TestRepository", "/", null, 0, false, "86fe5850-ab94-44e4-9bb2-fb364318e80c", ".\\RepositoryImages\\iOS_WS_TestRepository86fe5850.rximgres")
        {
            _compentairpentairhome = new iOS_WS_TestRepositoryFolders.ComPentairPentairhomeAppFolder(this);
            _productsupport_linkInfo = new RepoItemInfo(this, "ProductSupport_link", "/mobileapp[@title='com.pentair.pentairhome']//container[@accessibilitylabel='Product Support']/container[@accessibilitylabel='Product Support']", 30000, null, "04ce3df4-2a2e-4431-a897-008b1f284f1a");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("86fe5850-ab94-44e4-9bb2-fb364318e80c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ProductSupport_link item.
        /// </summary>
        [RepositoryItem("04ce3df4-2a2e-4431-a897-008b1f284f1a")]
        public virtual Ranorex.Container ProductSupport_link
        {
            get
            {
                 return _productsupport_linkInfo.CreateAdapter<Ranorex.Container>(true);
            }
        }

        /// <summary>
        /// The ProductSupport_link item info.
        /// </summary>
        [RepositoryItemInfo("04ce3df4-2a2e-4431-a897-008b1f284f1a")]
        public virtual RepoItemInfo ProductSupport_linkInfo
        {
            get
            {
                return _productsupport_linkInfo;
            }
        }

        /// <summary>
        /// The ComPentairPentairhome folder.
        /// </summary>
        [RepositoryFolder("20765b57-bbda-47ea-ae60-0a314b7708c4")]
        public virtual iOS_WS_TestRepositoryFolders.ComPentairPentairhomeAppFolder ComPentairPentairhome
        {
            get { return _compentairpentairhome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class iOS_WS_TestRepositoryFolders
    {
        /// <summary>
        /// The ComPentairPentairhomeAppFolder folder.
        /// </summary>
        [RepositoryFolder("20765b57-bbda-47ea-ae60-0a314b7708c4")]
        public partial class ComPentairPentairhomeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextInfo;
            RepoItemInfo _loginpageheaderInfo;
            RepoItemInfo _login_fieldInfo;
            RepoItemInfo _password_fieldInfo;
            RepoItemInfo _login_btnInfo;
            RepoItemInfo _common_dashboard_headerInfo;
            RepoItemInfo _adddevice_homedasboardInfo;
            RepoItemInfo _homedash_headerInfo;
            RepoItemInfo _device_tabInfo;
            RepoItemInfo _estsaltlevel_tileInfo;
            RepoItemInfo _waterusage_tileInfo;
            RepoItemInfo _waterusage_graphheaderInfo;
            RepoItemInfo _backarrouw_wsgInfo;
            RepoItemInfo _ws_iconInfo;
            RepoItemInfo _productoverview_linkInfo;
            RepoItemInfo _notifications_linkInfo;
            RepoItemInfo _mydevicewsInfo;
            RepoItemInfo _ws_listInfo;
            RepoItemInfo _header_wsdashboardInfo;
            RepoItemInfo _testwsautomation_listInfo;
            RepoItemInfo _setting_iconInfo;
            RepoItemInfo _nickname_prod_settingInfo;
            RepoItemInfo _remotemonitoring_linkInfo;
            RepoItemInfo _contactaprofessional_linkInfo;
            RepoItemInfo _wifi_linkInfo;
            RepoItemInfo _adjustsalt_linkInfo;
            RepoItemInfo _waterusagedetails_linkInfo;
            RepoItemInfo _removedevice_linkInfo;
            RepoItemInfo _productoverview_headerInfo;
            RepoItemInfo _manufacturerpentair_fieldInfo;
            RepoItemInfo _deviceidInfo;
            RepoItemInfo _modelInfo;
            RepoItemInfo _controllersoftwareversionInfo;
            RepoItemInfo _iotsoftwareversionInfo;
            RepoItemInfo _nicknametestwsautomationInfo;
            RepoItemInfo _addressInfo;
            RepoItemInfo _backarrow_poInfo;
            RepoItemInfo _checkyoursaltlevel_headerInfo;
            RepoItemInfo _statictext_cyslInfo;
            RepoItemInfo _notreadyfor_saltrefillInfo;
            RepoItemInfo _waterabovemysaltInfo;
            RepoItemInfo _outofsaltInfo;
            RepoItemInfo _salttankInfo;
            RepoItemInfo _estimatedsaltlevels_textInfo;
            RepoItemInfo _add_buttonInfo;
            RepoItemInfo _remove_buttonInfo;
            RepoItemInfo _saltamount_fieldInfo;
            RepoItemInfo _adjustsalt_buttonInfo;
            RepoItemInfo _adjustsaltconfirmationInfo;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _confirmInfo;
            RepoItemInfo _saltaddedInfo;
            RepoItemInfo _continueInfo;
            RepoItemInfo _adjustsaltheaderInfo;
            RepoItemInfo _date_fieldInfo;
            RepoItemInfo _notifications_headerInfo;
            RepoItemInfo _allnotificationsInfo;
            RepoItemInfo _toggle_allInfo;
            RepoItemInfo _backarrow_notificationsInfo;
            RepoItemInfo _productsupport_headerInfo;
            RepoItemInfo _connectedsoftenersupportInfo;
            RepoItemInfo _backarrow_psInfo;
            RepoItemInfo _wifi_headerInfo;
            RepoItemInfo _networknameInfo;
            RepoItemInfo _signalstrengthInfo;
            RepoItemInfo _changewifinetworkInfo;
            RepoItemInfo _bluetoothpairingscreenInfo;
            RepoItemInfo _backarrow_btpairInfo;
            RepoItemInfo _backarrow_wifiInfo;
            RepoItemInfo _water_usagedays_countInfo;
            RepoItemInfo _ws_devicelistInfo;
            RepoItemInfo _account_headerInfo;
            RepoItemInfo _accountstabInfo;
            RepoItemInfo _logoutlinkInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _swipeleft1Info;
            RepoItemInfo _swipeleft2Info;
            RepoItemInfo _swipeleft3Info;
            RepoItemInfo _nextbuttonInfo;

            /// <summary>
            /// Creates a new ComPentairPentairhome  folder.
            /// </summary>
            public ComPentairPentairhomeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComPentairPentairhome", "/mobileapp[@title='com.pentair.pentairhome']", parentFolder, 30000, null, false, "20765b57-bbda-47ea-ae60-0a314b7708c4", "")
            {
                _nextInfo = new RepoItemInfo(this, "NEXT", ".//container[@accessibilitylabel='NEXT']/container[@accessibilitylabel='NEXT']", 30000, null, "da4c4020-21d3-427d-a9f5-3f4d22d56730");
                _loginpageheaderInfo = new RepoItemInfo(this, "LogInPageHeader", ".//container[@accessibilitylabel='Log In']/container[@accessibilitylabel='Log In']", 30000, null, "d50396e5-f07c-455a-a22c-5991ac7e3aff");
                _login_fieldInfo = new RepoItemInfo(this, "Login_Field", ".//text[@accessibilityid='LoginTextInputEmail']", 30000, null, "2bdada8f-5281-4305-87bd-2a4fa8a3ae28");
                _password_fieldInfo = new RepoItemInfo(this, "Password_Field", ".//text[@accessibilityid='LoginTextInputPassword']", 30000, null, "a543a69a-9a0a-4588-9223-3aba33e91fc4");
                _login_btnInfo = new RepoItemInfo(this, "LOGIN_Btn", ".//container[@accessibilitylabel='LOG IN']", 30000, null, "dfbf3074-ef02-4e0e-a948-37e118ef7c0c");
                _common_dashboard_headerInfo = new RepoItemInfo(this, "Common_Dashboard_Header", ".//container[@accessibilityid='headerImage']", 30000, null, "72c99ee0-5e5c-4a9f-9d22-5b3d8a72132c");
                _adddevice_homedasboardInfo = new RepoItemInfo(this, "AddDevice_HomeDasboard", ".//container[@accessibilitylabel='Add a Device']/container[@accessibilitylabel='Add a Device']", 30000, null, "522ac32c-8b87-4a25-a670-4ee4aff265b2");
                _homedash_headerInfo = new RepoItemInfo(this, "HomeDash_Header", ".//container[@accessibilitylabel='assets/src/Common_Feature/Images/whiteLogo@3x.png']", 30000, null, "502370f8-5dca-44b7-9928-495abb457bce");
                _device_tabInfo = new RepoItemInfo(this, "Device_Tab", ".//container[@accessibilitylabel='assets/src/Common_Feature/Images/device@3x.png']", 30000, null, "35a3285d-e6f1-4cff-bbd7-fc32e7030ebc");
                _estsaltlevel_tileInfo = new RepoItemInfo(this, "EstSaltLevel_tile", ".//container[@accessibilitylabel='Est. Salt Level']/container[@accessibilitylabel='Est. Salt Level']/container[@accessibilitylabel='Est. Salt Level']", 30000, null, "9affb078-f46f-4b00-8203-3f701ceb6c5c");
                _waterusage_tileInfo = new RepoItemInfo(this, "WaterUsage_Tile", ".//container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']", 30000, null, "16609578-3ddf-4590-85f2-c02ad9d23bda");
                _waterusage_graphheaderInfo = new RepoItemInfo(this, "WaterUsage_graphHeader", ".//container[@accessibilitylabel='Water Usage Gallons Per Day Daily Weekly Monthly Yearly No Data Vertical scroll bar, 1 page Horizontal scroll bar, 1 page']/container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']/container[@accessibilitylabel='Water Usage']", 30000, null, "bbccec1d-68d8-4ea6-a511-fe587b88592a");
                _backarrouw_wsgInfo = new RepoItemInfo(this, "BackArrouw_WSG", ".//container[@accessibilitylabel='Water Usage']/container[2]/container[@caption='']/container[@caption='']", 30000, null, "6d864379-6ad6-444b-b845-1f0320a37869");
                _ws_iconInfo = new RepoItemInfo(this, "WS_icon", ".//container[@accessibilitylabel='assets/src/Common_Feature/Images/waterSoftener@3x.png']", 30000, null, "8ba576ac-19e3-48cf-9ecd-6454339a0d0d");
                _productoverview_linkInfo = new RepoItemInfo(this, "ProductOverview_Link", ".//container[@accessibilitylabel='Product Overview']/container[@accessibilitylabel='Product Overview']", 30000, null, "98984af6-0e31-4968-bb29-f53461af2685");
                _notifications_linkInfo = new RepoItemInfo(this, "Notifications_link", ".//container[@accessibilitylabel='Notifications']/container[@accessibilitylabel='Notifications']", 30000, null, "f84a0ad0-38c8-4c41-ba4f-3d53533b9949");
                _mydevicewsInfo = new RepoItemInfo(this, "MyDeviceWS", ".//container[@accessibilitylabel='Home Test 22 Manpreet alok Test']/container[@accessibilitylabel='Test 22']/container[@accessibilitylabel='Test 22']/container[@accessibilitylabel='Test 22']/container[@accessibilitylabel='Test 22']/container[@accessibilitylabel='Test 22']", 30000, null, "2588f1f9-133c-4b49-b488-3961eabdbf15");
                _ws_listInfo = new RepoItemInfo(this, "WS_List", ".//container[@accessibilitylabel='Home Tanmay Manpreet Ss']/container[@accessibilitylabel='Tanmay']/container[@accessibilitylabel='Tanmay']/container[@accessibilitylabel='Tanmay']", 30000, null, "a0412231-ff69-47f8-b2de-2fff909cd344");
                _header_wsdashboardInfo = new RepoItemInfo(this, "Header_WSDashboard", ".//container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']", 30000, null, "c9b1f189-cde7-4b68-8015-a08111fa48d3");
                _testwsautomation_listInfo = new RepoItemInfo(this, "TestWSAutomation_List", ".//container[@accessibilitylabel='Home Manpreet Ss Other Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']", 30000, null, "cc46b818-05f2-42ed-8a5d-17815f505b8f");
                _setting_iconInfo = new RepoItemInfo(this, "Setting_Icon", ".//container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[2]/container[@caption='']/container[@accessibilityid='headerRightImage']/container[@caption='']", 30000, null, "0f7860ec-c4ec-4247-830c-0a4a58a4d6ef");
                _nickname_prod_settingInfo = new RepoItemInfo(this, "NickName_Prod_Setting", ".//container[@accessibilitylabel=' Test WS Automation']/container[@accessibilitylabel='Test WS Automation']", 30000, null, "7d2432d3-9350-4971-8069-108fea843f19");
                _remotemonitoring_linkInfo = new RepoItemInfo(this, "RemoteMonitoring_Link", ".//container[@accessibilitylabel='Remote Monitoring']/container[@accessibilitylabel='Remote Monitoring']", 30000, null, "b2ddc209-1f2d-4f82-ab52-50644e07b407");
                _contactaprofessional_linkInfo = new RepoItemInfo(this, "ContactAProfessional_link", ".//container[@accessibilitylabel='Contact a Professional']", 30000, null, "adf790f6-3633-4561-bc78-40983073bf8e");
                _wifi_linkInfo = new RepoItemInfo(this, "WiFi_link", ".//container[@accessibilitylabel='WiFi']", 30000, null, "776fe94d-0fdd-45fc-a52b-0383b4fea351");
                _adjustsalt_linkInfo = new RepoItemInfo(this, "AdjustSalt_link", ".//container[@accessibilitylabel='Adjust Salt']", 30000, null, "85dfcc15-b4eb-4467-8bc0-a9678d13d250");
                _waterusagedetails_linkInfo = new RepoItemInfo(this, "WaterUsageDetails_link", ".//container[@accessibilitylabel='Water Usage Details']", 30000, null, "d2e5fac0-3e23-43e7-b216-90c940a9f6e5");
                _removedevice_linkInfo = new RepoItemInfo(this, "RemoveDevice_link", ".//container[@accessibilitylabel='Remove Device']", 30000, null, "12cead18-1b12-466e-90fb-7b064c034f6a");
                _productoverview_headerInfo = new RepoItemInfo(this, "ProductOverview_Header", ".//container[@accessibilitylabel='Product Overview']", 30000, null, "8774d333-7c08-4f86-b261-d94f1c8a1cbf");
                _manufacturerpentair_fieldInfo = new RepoItemInfo(this, "ManufacturerPentair_field", ".//container[@accessibilitylabel='Manufacturer Pentair']/container[@accessibilitylabel='Manufacturer Pentair']/container[@accessibilitylabel='Manufacturer Pentair']/container[@accessibilitylabel='Manufacturer Pentair']", 30000, null, "a01f896b-6954-484b-a1c5-7378743fe52e");
                _deviceidInfo = new RepoItemInfo(this, "DeviceID", ".//container[@accessibilitylabel='Device ID PNR01XTR10000030A3']/container[@accessibilitylabel='Device ID PNR01XTR10000030A3']", 30000, null, "063180a5-840d-4346-a9b1-7b2dab693c81");
                _modelInfo = new RepoItemInfo(this, "Model", ".//container[@accessibilitylabel='Model XTR2']/container[@accessibilitylabel='Model XTR2']/container[@accessibilitylabel='Model XTR2']", 30000, null, "ea9aa73a-7a53-4cbb-8e33-7f0ba0fa9747");
                _controllersoftwareversionInfo = new RepoItemInfo(this, "ControllerSoftwareVersion", ".//container[@accessibilitylabel='Controller Software Version 3.1.03.1892']/container[@accessibilitylabel='Controller Software Version 3.1.03.1892']/container[@accessibilitylabel='Controller Software Version 3.1.03.1892']", 30000, null, "299fa8a5-252b-43d4-aaef-75f5a394f0d8");
                _iotsoftwareversionInfo = new RepoItemInfo(this, "IoTSoftwareVersion", ".//container[@accessibilitylabel='IoT Software Version 2.8']/container[@accessibilitylabel='IoT Software Version 2.8']", 30000, null, "3c8c1d3b-84cf-4ac0-be20-34c81c986956");
                _nicknametestwsautomationInfo = new RepoItemInfo(this, "NicknameTestWSAutomation", ".//container[@accessibilitylabel='Nickname Test WS Automation']/container[@accessibilitylabel='Nickname Test WS Automation']", 30000, null, "309e3e5c-bf42-4a48-81a8-83ee58c1b3db");
                _addressInfo = new RepoItemInfo(this, "Address", ".//container[@accessibilitylabel='Address N/A']/container[@accessibilitylabel='Address N/A']", 30000, null, "b6b33cfa-2d0d-4b60-96c4-ddbcdf0ace68");
                _backarrow_poInfo = new RepoItemInfo(this, "BackArrow_PO", ".//container[@accessibilitylabel=' Product Overview']/container[@accessibilitylabel='']/container[@accessibilitylabel='']", 30000, null, "55a6fd3e-feb0-4d09-972e-ebe1e0cec156");
                _checkyoursaltlevel_headerInfo = new RepoItemInfo(this, "CheckYourSaltLevel_Header", ".//container[@accessibilitylabel='Check Your Salt Level Before adding salt, please check your brine tank and indicate the salt level: I’m not ready for a salt refill. I can see water above my salt. I am out of salt. Vertical scroll bar, 1 page Horizontal scroll bar, 1 page Vertical scroll bar, 1 page Horizontal scroll bar, 1 page']/container[@accessibilitylabel='Check Your Salt Level']/container[@accessibilitylabel='Check Your Salt Level']/container[@accessibilitylabel='Check Your Salt Level']/container[@accessibilitylabel='Check Your Salt Level']/container[@accessibilitylabel='Check Your Salt Level']/container[@accessibilitylabel='Check Your Salt Level']/container[@accessibilitylabel='Check Your Salt Level']", 30000, null, "311c773b-f216-4dfa-8ae0-9431a0ddd049");
                _statictext_cyslInfo = new RepoItemInfo(this, "StaticText_CYSL", ".//container[@accessibilitylabel='Before adding salt, please check your brine tank and indicate the salt level:']", 30000, null, "c88b6d23-e6a7-4264-ad95-c09472c2f6f4");
                _notreadyfor_saltrefillInfo = new RepoItemInfo(this, "NotReadyFor_SaltRefill", ".//container[@accessibilitylabel='I’m not ready for a salt refill.']/container[@accessibilitylabel='I’m not ready for a salt refill.']/container[@accessibilitylabel='I’m not ready for a salt refill.']/container[@accessibilitylabel='I’m not ready for a salt refill.']", 30000, null, "cd291815-9967-4852-ae0d-054402cfde4f");
                _waterabovemysaltInfo = new RepoItemInfo(this, "WaterAboveMySalt", ".//container[@accessibilitylabel='I can see water above my salt.']/container[@accessibilitylabel='I can see water above my salt.']/container[@accessibilitylabel='I can see water above my salt.']/container[@accessibilitylabel='I can see water above my salt.']", 30000, null, "d6e11cee-f87f-4513-83bd-725219bb0991");
                _outofsaltInfo = new RepoItemInfo(this, "OutOfSalt", ".//container[@accessibilitylabel='I am out of salt.']/container[@accessibilitylabel='I am out of salt.']", 30000, null, "9e3a53b4-82a8-4f9a-ac2a-225670385f4d");
                _salttankInfo = new RepoItemInfo(this, "SaltTank", ".//container[@accessibilitylabel='Estimated Salt Levels 259 lb']/container[1]", 30000, null, "0b3a591f-d337-42dc-81fd-097aa1ebc7f5");
                _estimatedsaltlevels_textInfo = new RepoItemInfo(this, "EstimatedSaltLevels_Text", ".//container[@accessibilitylabel='Estimated Salt Levels']", 30000, null, "bb56f285-cca5-4248-a1ed-aef288049317");
                _add_buttonInfo = new RepoItemInfo(this, "Add_Button", ".//container[@accessibilitylabel=' Add ']", 30000, null, "86dbb929-8bc7-48ee-a768-b374d531eaba");
                _remove_buttonInfo = new RepoItemInfo(this, "Remove_Button", ".//container[@accessibilitylabel=' Remove ']/container[@accessibilitylabel=' Remove ']", 30000, null, "802c7d5e-5986-48c6-90da-94eb3230cee0");
                _saltamount_fieldInfo = new RepoItemInfo(this, "SaltAmount_Field", ".//container[@accessibilitylabel='0']", 30000, null, "b3a13fe7-6b8a-4843-a7ef-42b581230787");
                _adjustsalt_buttonInfo = new RepoItemInfo(this, "ADJUSTSALT_button", ".//container[@accessibilitylabel='ADJUST SALT']/container[@accessibilitylabel='ADJUST SALT']", 30000, null, "51eb93fc-7693-4100-8ffc-c33306b708f1");
                _adjustsaltconfirmationInfo = new RepoItemInfo(this, "AdjustSaltConfirmation", ".//container[@accessibilitylabel='Adjust Salt Confirmation']/container[@accessibilitylabel='Adjust Salt Confirmation']", 30000, null, "f4ba9c06-8a92-4d53-b836-7d06026891c4");
                _cancelInfo = new RepoItemInfo(this, "CANCEL", ".//container", 30000, null, "cb892f95-79b8-4893-b256-c1c8b32568bf");
                _confirmInfo = new RepoItemInfo(this, "CONFIRM", ".//container[@accessibilitylabel='CONFIRM']", 30000, null, "a439e746-5255-4d31-8698-14d29e998f9e");
                _saltaddedInfo = new RepoItemInfo(this, "SaltAdded", ".//container[@accessibilitylabel='Salt Added']", 30000, null, "2a1813f5-70d3-4063-b90d-20d4342c1ed7");
                _continueInfo = new RepoItemInfo(this, "CONTINUE", ".//container[@accessibilitylabel='CONTINUE']/container[@accessibilitylabel='CONTINUE']", 30000, null, "604c22ac-4d07-4fd7-8b62-72d4f83b5bb7");
                _adjustsaltheaderInfo = new RepoItemInfo(this, "AdjustSaltHeader", ".//container[@accessibilitylabel='Adjust Salt Estimated Salt Levels 259 lb  Add   Remove  Salt Amount (lb) 0 Adjustment Date 07/21/2020 ADJUST SALT Vertical scroll bar, 1 page Horizontal scroll bar, 1 page']/container[@accessibilitylabel='Adjust Salt']/container[@accessibilitylabel='Adjust Salt']", 30000, null, "aec00056-027a-4f59-b9d3-b0ed61ed3670");
                _date_fieldInfo = new RepoItemInfo(this, "Date_Field", ".//container[@accessibilitylabel='07/21/2020']/container[@accessibilitylabel='07/21/2020']", 30000, null, "0c668032-4fa5-4935-988e-ee09a789aae1");
                _notifications_headerInfo = new RepoItemInfo(this, "Notifications_Header", ".//container[@accessibilitylabel='Notifications']", 30000, null, "200b855a-eead-4db0-872b-41df242db261");
                _allnotificationsInfo = new RepoItemInfo(this, "AllNotifications", ".//container[@accessibilitylabel='All Notifications']/container[@accessibilitylabel='All Notifications']/container[@accessibilitylabel='All Notifications']/container[@accessibilitylabel='All Notifications']/container[@accessibilitylabel='All Notifications']/container[@accessibilitylabel='All Notifications']/container[@accessibilitylabel='All Notifications']/container[@accessibilitylabel='All Notifications']", 30000, null, "bcbdd62e-92cf-4669-a637-3656f6495805");
                _toggle_allInfo = new RepoItemInfo(this, "Toggle_All", ".//container[@accessibilityid='toggle']", 30000, null, "f4806dc7-3f45-474c-825b-be08822413e4");
                _backarrow_notificationsInfo = new RepoItemInfo(this, "Backarrow_Notifications", ".//container[@accessibilitylabel='Notifications']/container[@accessibilitylabel='Notifications']/container[1]/container[@caption='']", 30000, null, "b824ec7f-9c26-4370-8bef-25a2568b4981");
                _productsupport_headerInfo = new RepoItemInfo(this, "ProductSupport_Header", ".//container[@accessibilitylabel='Product Support']/container[@accessibilitylabel='Product Support']/container[@accessibilitylabel='Product Support']/container[@accessibilitylabel='Product Support']", 30000, null, "dbcad9a9-1f96-4736-b393-207654c1ce30");
                _connectedsoftenersupportInfo = new RepoItemInfo(this, "ConnectedSoftenerSupport", ".//dom[@domain='www.pentair.com']//h2[@innertext>'Connected Softener Suppor']", 30000, null, "b7fa124e-06f1-4eb5-bb00-2d08ef43c45a");
                _backarrow_psInfo = new RepoItemInfo(this, "backArrow_PS", ".//container[@accessibilitylabel='Product Support']/container[@accessibilitylabel='Product Support']/container[@accessibilitylabel='Product Support']/container[1]/container[@caption='']", 30000, null, "76fbc474-4f96-46fc-b5c3-ebebfbdd5b25");
                _wifi_headerInfo = new RepoItemInfo(this, "WiFi_Header", ".//container[@accessibilitylabel='WiFi']/container[@accessibilitylabel='WiFi']", 30000, null, "3280c09b-59b0-4e86-8c58-32f428c62c8d");
                _networknameInfo = new RepoItemInfo(this, "NetworkName", ".//container[@accessibilitylabel='Network Amogha']", 30000, null, "42597f4c-8345-4f12-b9cf-85130bda6340");
                _signalstrengthInfo = new RepoItemInfo(this, "SignalStrength", ".//container[@accessibilitylabel='Signal Strength']", 30000, null, "c804621c-b115-42dd-ae52-faac2f21098b");
                _changewifinetworkInfo = new RepoItemInfo(this, "ChangeWiFiNetwork", ".//container[@accessibilitylabel='Change WiFi Network']/container[@accessibilitylabel='Change WiFi Network']", 30000, null, "2ce730b0-085a-4964-8ada-40e1cf54d121");
                _bluetoothpairingscreenInfo = new RepoItemInfo(this, "BluetoothPairingScreen", ".//container[@accessibilitylabel='Bluetooth Pairing Is your Water Softener in pairing mode? Please refer to user manual to enable Bluetooth Pairing. CONTINUE']", 30000, null, "976b6d0e-a5f5-4345-bc91-0ee11223162f");
                _backarrow_btpairInfo = new RepoItemInfo(this, "BackArrow_BTPair", ".//container[@accessibilitylabel='Bluetooth Pairing Is your Water Softener in pairing mode? Please refer to user manual to enable Bluetooth Pairing. CONTINUE Vertical scroll bar, 1 page Horizontal scroll bar, 1 page']/container[@accessibilitylabel='Bluetooth Pairing Is your Water Softener in pairing mode? Please refer to user manual to enable Bluetooth Pairing. CONTINUE Vertical scroll bar, 1 page Horizontal scroll bar, 1 page']/container[@accessibilitylabel='Bluetooth Pairing Is your Water Softener in pairing mode? Please refer to user manual to enable Bluetooth Pairing. CONTINUE Vertical scroll bar, 1 page Horizontal scroll bar, 1 page']/container[1]/container[@caption='']/container[@caption='']/container[1]/container[@caption='']/container[@caption='']/container[@caption='']", 30000, null, "93895b2d-d744-4ddf-b606-7efaf29023c7");
                _backarrow_wifiInfo = new RepoItemInfo(this, "BackArrow_WiFi", ".//container[@accessibilitylabel='WiFi']/container[@accessibilitylabel='WiFi']/container[1]/container[@caption='']", 30000, null, "883be278-0007-4d6f-aec2-670cf43f28f2");
                _water_usagedays_countInfo = new RepoItemInfo(this, "Water_UsageDays_count", ".//container[@accessibilitylabel='Today,  Jul 21, 2020 Jul 20, 2020 Jul 19, 2020 Jul 18, 2020 Jul 17, 2020 Jul 16, 2020 Jul 15, 2020']", 30000, null, "f2890560-ae72-4392-b4cc-0c814f99f819");
                _ws_devicelistInfo = new RepoItemInfo(this, "WS_deviceList", ".//container[@accessibilitylabel='Home Manpreet Test SS Other Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']/container[@accessibilitylabel='Test WS Automation']", 30000, null, "2fba6e87-9225-406b-97ac-f59911b9cc2d");
                _account_headerInfo = new RepoItemInfo(this, "Account_Header", ".//container[@accessibilitylabel='Account Edit Profile Pool Info Notifications Contact a Professional Warranties Legal Contact Pentair Log Out Vertical scroll bar, 1 page Horizontal scroll bar, 1 page  Version 2.2.9(4111) Vertical scroll bar, 1 page Horizontal scroll bar, 1 page']/container[@accessibilitylabel='Account']/container[@accessibilitylabel='Account']/container[@accessibilitylabel='Account']/container[@accessibilitylabel='Account']/container[@accessibilitylabel='Account']/container[@accessibilitylabel='Account']/container[@accessibilitylabel='Account']", 30000, null, "cd7cb1a7-c3d8-4026-8094-bb8201e2de53");
                _accountstabInfo = new RepoItemInfo(this, "AccountsTab", "form/container[1]/container[@caption='']/container/container/container/container/container/container/container/container/container[2]/container/container/container[1]/container/container[2]/container/container[2]/container[@caption='']/container[4]", 30000, null, "65ef31ec-709d-4a12-a52c-c8a129142938");
                _logoutlinkInfo = new RepoItemInfo(this, "LogOutlink", ".//container[@accessibilitylabel='Log Out']/container[@accessibilitylabel='Log Out']/container[@accessibilitylabel='Log Out']/container[@accessibilitylabel='Log Out']/container[@accessibilitylabel='Log Out']", 30000, null, "06136611-3384-4857-9593-6f8144f99685");
                _logoutInfo = new RepoItemInfo(this, "LogOut", ".//container[@accessibilitylabel='Cancel Log Out']/container[@accessibilitylabel='Log Out']/container[@accessibilitylabel='Log Out']/container[@accessibilitylabel='Log Out']", 30000, null, "e2439326-43e2-487e-8fa1-8762c2b13ee0");
                _swipeleft1Info = new RepoItemInfo(this, "SwipeLeft1", ".//container[@accessibilitylabel='Take control of your home’s water Stay smart, connected and protected.']/container[@accessibilitylabel='Take control of your home’s water Stay smart, connected and protected.']/container[1]/container[@caption='']/container[@caption='']", 30000, null, "3869091b-9042-49f3-aac5-2819e5f5578d");
                _swipeleft2Info = new RepoItemInfo(this, "SwipeLeft2", ".//container[@accessibilitylabel='Manage systems on the go. Get status information, home or away, 24/7.']/container[@accessibilitylabel='Manage systems on the go. Get status information, home or away, 24/7.']/container[1]", 30000, null, "2c965b51-04b3-4e75-9e4a-03114a74a05d");
                _swipeleft3Info = new RepoItemInfo(this, "SwipeLeft3", ".//container[@accessibilitylabel='We’ll let you know, what to do, when. Receive alerts sent to your phone-and if you choose-your trusted pros.']/container[@accessibilitylabel='We’ll let you know, what to do, when. Receive alerts sent to your phone-and if you choose-your trusted pros.']/container[1]", 30000, null, "3dc32ceb-e1d4-4362-b909-c1153210ca7e");
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", ".//container[@accessibilityid='AppWalkthroughNextButton']", 30000, null, "2730181c-3ad2-46dd-ae4e-380c60a93dbc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("20765b57-bbda-47ea-ae60-0a314b7708c4")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("20765b57-bbda-47ea-ae60-0a314b7708c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NEXT item.
            /// </summary>
            [RepositoryItem("da4c4020-21d3-427d-a9f5-3f4d22d56730")]
            public virtual Ranorex.Container NEXT
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NEXT item info.
            /// </summary>
            [RepositoryItemInfo("da4c4020-21d3-427d-a9f5-3f4d22d56730")]
            public virtual RepoItemInfo NEXTInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The LogInPageHeader item.
            /// </summary>
            [RepositoryItem("d50396e5-f07c-455a-a22c-5991ac7e3aff")]
            public virtual Ranorex.Container LogInPageHeader
            {
                get
                {
                    return _loginpageheaderInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The LogInPageHeader item info.
            /// </summary>
            [RepositoryItemInfo("d50396e5-f07c-455a-a22c-5991ac7e3aff")]
            public virtual RepoItemInfo LogInPageHeaderInfo
            {
                get
                {
                    return _loginpageheaderInfo;
                }
            }

            /// <summary>
            /// The Login_Field item.
            /// </summary>
            [RepositoryItem("2bdada8f-5281-4305-87bd-2a4fa8a3ae28")]
            public virtual Ranorex.Text Login_Field
            {
                get
                {
                    return _login_fieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Login_Field item info.
            /// </summary>
            [RepositoryItemInfo("2bdada8f-5281-4305-87bd-2a4fa8a3ae28")]
            public virtual RepoItemInfo Login_FieldInfo
            {
                get
                {
                    return _login_fieldInfo;
                }
            }

            /// <summary>
            /// The Password_Field item.
            /// </summary>
            [RepositoryItem("a543a69a-9a0a-4588-9223-3aba33e91fc4")]
            public virtual Ranorex.Text Password_Field
            {
                get
                {
                    return _password_fieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password_Field item info.
            /// </summary>
            [RepositoryItemInfo("a543a69a-9a0a-4588-9223-3aba33e91fc4")]
            public virtual RepoItemInfo Password_FieldInfo
            {
                get
                {
                    return _password_fieldInfo;
                }
            }

            /// <summary>
            /// The LOGIN_Btn item.
            /// </summary>
            [RepositoryItem("dfbf3074-ef02-4e0e-a948-37e118ef7c0c")]
            public virtual Ranorex.Container LOGIN_Btn
            {
                get
                {
                    return _login_btnInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The LOGIN_Btn item info.
            /// </summary>
            [RepositoryItemInfo("dfbf3074-ef02-4e0e-a948-37e118ef7c0c")]
            public virtual RepoItemInfo LOGIN_BtnInfo
            {
                get
                {
                    return _login_btnInfo;
                }
            }

            /// <summary>
            /// The Common_Dashboard_Header item.
            /// </summary>
            [RepositoryItem("72c99ee0-5e5c-4a9f-9d22-5b3d8a72132c")]
            public virtual Ranorex.Container Common_Dashboard_Header
            {
                get
                {
                    return _common_dashboard_headerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Common_Dashboard_Header item info.
            /// </summary>
            [RepositoryItemInfo("72c99ee0-5e5c-4a9f-9d22-5b3d8a72132c")]
            public virtual RepoItemInfo Common_Dashboard_HeaderInfo
            {
                get
                {
                    return _common_dashboard_headerInfo;
                }
            }

            /// <summary>
            /// The AddDevice_HomeDasboard item.
            /// </summary>
            [RepositoryItem("522ac32c-8b87-4a25-a670-4ee4aff265b2")]
            public virtual Ranorex.Container AddDevice_HomeDasboard
            {
                get
                {
                    return _adddevice_homedasboardInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AddDevice_HomeDasboard item info.
            /// </summary>
            [RepositoryItemInfo("522ac32c-8b87-4a25-a670-4ee4aff265b2")]
            public virtual RepoItemInfo AddDevice_HomeDasboardInfo
            {
                get
                {
                    return _adddevice_homedasboardInfo;
                }
            }

            /// <summary>
            /// The HomeDash_Header item.
            /// </summary>
            [RepositoryItem("502370f8-5dca-44b7-9928-495abb457bce")]
            public virtual Ranorex.Container HomeDash_Header
            {
                get
                {
                    return _homedash_headerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The HomeDash_Header item info.
            /// </summary>
            [RepositoryItemInfo("502370f8-5dca-44b7-9928-495abb457bce")]
            public virtual RepoItemInfo HomeDash_HeaderInfo
            {
                get
                {
                    return _homedash_headerInfo;
                }
            }

            /// <summary>
            /// The Device_Tab item.
            /// </summary>
            [RepositoryItem("35a3285d-e6f1-4cff-bbd7-fc32e7030ebc")]
            public virtual Ranorex.Container Device_Tab
            {
                get
                {
                    return _device_tabInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Device_Tab item info.
            /// </summary>
            [RepositoryItemInfo("35a3285d-e6f1-4cff-bbd7-fc32e7030ebc")]
            public virtual RepoItemInfo Device_TabInfo
            {
                get
                {
                    return _device_tabInfo;
                }
            }

            /// <summary>
            /// The EstSaltLevel_tile item.
            /// </summary>
            [RepositoryItem("9affb078-f46f-4b00-8203-3f701ceb6c5c")]
            public virtual Ranorex.Container EstSaltLevel_tile
            {
                get
                {
                    return _estsaltlevel_tileInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The EstSaltLevel_tile item info.
            /// </summary>
            [RepositoryItemInfo("9affb078-f46f-4b00-8203-3f701ceb6c5c")]
            public virtual RepoItemInfo EstSaltLevel_tileInfo
            {
                get
                {
                    return _estsaltlevel_tileInfo;
                }
            }

            /// <summary>
            /// The WaterUsage_Tile item.
            /// </summary>
            [RepositoryItem("16609578-3ddf-4590-85f2-c02ad9d23bda")]
            public virtual Ranorex.Container WaterUsage_Tile
            {
                get
                {
                    return _waterusage_tileInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WaterUsage_Tile item info.
            /// </summary>
            [RepositoryItemInfo("16609578-3ddf-4590-85f2-c02ad9d23bda")]
            public virtual RepoItemInfo WaterUsage_TileInfo
            {
                get
                {
                    return _waterusage_tileInfo;
                }
            }

            /// <summary>
            /// The WaterUsage_graphHeader item.
            /// </summary>
            [RepositoryItem("bbccec1d-68d8-4ea6-a511-fe587b88592a")]
            public virtual Ranorex.Container WaterUsage_graphHeader
            {
                get
                {
                    return _waterusage_graphheaderInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WaterUsage_graphHeader item info.
            /// </summary>
            [RepositoryItemInfo("bbccec1d-68d8-4ea6-a511-fe587b88592a")]
            public virtual RepoItemInfo WaterUsage_graphHeaderInfo
            {
                get
                {
                    return _waterusage_graphheaderInfo;
                }
            }

            /// <summary>
            /// The BackArrouw_WSG item.
            /// </summary>
            [RepositoryItem("6d864379-6ad6-444b-b845-1f0320a37869")]
            public virtual Ranorex.Container BackArrouw_WSG
            {
                get
                {
                    return _backarrouw_wsgInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BackArrouw_WSG item info.
            /// </summary>
            [RepositoryItemInfo("6d864379-6ad6-444b-b845-1f0320a37869")]
            public virtual RepoItemInfo BackArrouw_WSGInfo
            {
                get
                {
                    return _backarrouw_wsgInfo;
                }
            }

            /// <summary>
            /// The WS_icon item.
            /// </summary>
            [RepositoryItem("8ba576ac-19e3-48cf-9ecd-6454339a0d0d")]
            public virtual Ranorex.Container WS_icon
            {
                get
                {
                    return _ws_iconInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WS_icon item info.
            /// </summary>
            [RepositoryItemInfo("8ba576ac-19e3-48cf-9ecd-6454339a0d0d")]
            public virtual RepoItemInfo WS_iconInfo
            {
                get
                {
                    return _ws_iconInfo;
                }
            }

            /// <summary>
            /// The ProductOverview_Link item.
            /// </summary>
            [RepositoryItem("98984af6-0e31-4968-bb29-f53461af2685")]
            public virtual Ranorex.Container ProductOverview_Link
            {
                get
                {
                    return _productoverview_linkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ProductOverview_Link item info.
            /// </summary>
            [RepositoryItemInfo("98984af6-0e31-4968-bb29-f53461af2685")]
            public virtual RepoItemInfo ProductOverview_LinkInfo
            {
                get
                {
                    return _productoverview_linkInfo;
                }
            }

            /// <summary>
            /// The Notifications_link item.
            /// </summary>
            [RepositoryItem("f84a0ad0-38c8-4c41-ba4f-3d53533b9949")]
            public virtual Ranorex.Container Notifications_link
            {
                get
                {
                    return _notifications_linkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Notifications_link item info.
            /// </summary>
            [RepositoryItemInfo("f84a0ad0-38c8-4c41-ba4f-3d53533b9949")]
            public virtual RepoItemInfo Notifications_linkInfo
            {
                get
                {
                    return _notifications_linkInfo;
                }
            }

            /// <summary>
            /// The MyDeviceWS item.
            /// </summary>
            [RepositoryItem("2588f1f9-133c-4b49-b488-3961eabdbf15")]
            public virtual Ranorex.Container MyDeviceWS
            {
                get
                {
                    return _mydevicewsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The MyDeviceWS item info.
            /// </summary>
            [RepositoryItemInfo("2588f1f9-133c-4b49-b488-3961eabdbf15")]
            public virtual RepoItemInfo MyDeviceWSInfo
            {
                get
                {
                    return _mydevicewsInfo;
                }
            }

            /// <summary>
            /// The WS_List item.
            /// </summary>
            [RepositoryItem("a0412231-ff69-47f8-b2de-2fff909cd344")]
            public virtual Ranorex.Container WS_List
            {
                get
                {
                    return _ws_listInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WS_List item info.
            /// </summary>
            [RepositoryItemInfo("a0412231-ff69-47f8-b2de-2fff909cd344")]
            public virtual RepoItemInfo WS_ListInfo
            {
                get
                {
                    return _ws_listInfo;
                }
            }

            /// <summary>
            /// The Header_WSDashboard item.
            /// </summary>
            [RepositoryItem("c9b1f189-cde7-4b68-8015-a08111fa48d3")]
            public virtual Ranorex.Container Header_WSDashboard
            {
                get
                {
                    return _header_wsdashboardInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Header_WSDashboard item info.
            /// </summary>
            [RepositoryItemInfo("c9b1f189-cde7-4b68-8015-a08111fa48d3")]
            public virtual RepoItemInfo Header_WSDashboardInfo
            {
                get
                {
                    return _header_wsdashboardInfo;
                }
            }

            /// <summary>
            /// The TestWSAutomation_List item.
            /// </summary>
            [RepositoryItem("cc46b818-05f2-42ed-8a5d-17815f505b8f")]
            public virtual Ranorex.Container TestWSAutomation_List
            {
                get
                {
                    return _testwsautomation_listInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TestWSAutomation_List item info.
            /// </summary>
            [RepositoryItemInfo("cc46b818-05f2-42ed-8a5d-17815f505b8f")]
            public virtual RepoItemInfo TestWSAutomation_ListInfo
            {
                get
                {
                    return _testwsautomation_listInfo;
                }
            }

            /// <summary>
            /// The Setting_Icon item.
            /// </summary>
            [RepositoryItem("0f7860ec-c4ec-4247-830c-0a4a58a4d6ef")]
            public virtual Ranorex.Container Setting_Icon
            {
                get
                {
                    return _setting_iconInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Setting_Icon item info.
            /// </summary>
            [RepositoryItemInfo("0f7860ec-c4ec-4247-830c-0a4a58a4d6ef")]
            public virtual RepoItemInfo Setting_IconInfo
            {
                get
                {
                    return _setting_iconInfo;
                }
            }

            /// <summary>
            /// The NickName_Prod_Setting item.
            /// </summary>
            [RepositoryItem("7d2432d3-9350-4971-8069-108fea843f19")]
            public virtual Ranorex.Container NickName_Prod_Setting
            {
                get
                {
                    return _nickname_prod_settingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NickName_Prod_Setting item info.
            /// </summary>
            [RepositoryItemInfo("7d2432d3-9350-4971-8069-108fea843f19")]
            public virtual RepoItemInfo NickName_Prod_SettingInfo
            {
                get
                {
                    return _nickname_prod_settingInfo;
                }
            }

            /// <summary>
            /// The RemoteMonitoring_Link item.
            /// </summary>
            [RepositoryItem("b2ddc209-1f2d-4f82-ab52-50644e07b407")]
            public virtual Ranorex.Container RemoteMonitoring_Link
            {
                get
                {
                    return _remotemonitoring_linkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RemoteMonitoring_Link item info.
            /// </summary>
            [RepositoryItemInfo("b2ddc209-1f2d-4f82-ab52-50644e07b407")]
            public virtual RepoItemInfo RemoteMonitoring_LinkInfo
            {
                get
                {
                    return _remotemonitoring_linkInfo;
                }
            }

            /// <summary>
            /// The ContactAProfessional_link item.
            /// </summary>
            [RepositoryItem("adf790f6-3633-4561-bc78-40983073bf8e")]
            public virtual Ranorex.Container ContactAProfessional_link
            {
                get
                {
                    return _contactaprofessional_linkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContactAProfessional_link item info.
            /// </summary>
            [RepositoryItemInfo("adf790f6-3633-4561-bc78-40983073bf8e")]
            public virtual RepoItemInfo ContactAProfessional_linkInfo
            {
                get
                {
                    return _contactaprofessional_linkInfo;
                }
            }

            /// <summary>
            /// The WiFi_link item.
            /// </summary>
            [RepositoryItem("776fe94d-0fdd-45fc-a52b-0383b4fea351")]
            public virtual Ranorex.Container WiFi_link
            {
                get
                {
                    return _wifi_linkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WiFi_link item info.
            /// </summary>
            [RepositoryItemInfo("776fe94d-0fdd-45fc-a52b-0383b4fea351")]
            public virtual RepoItemInfo WiFi_linkInfo
            {
                get
                {
                    return _wifi_linkInfo;
                }
            }

            /// <summary>
            /// The AdjustSalt_link item.
            /// </summary>
            [RepositoryItem("85dfcc15-b4eb-4467-8bc0-a9678d13d250")]
            public virtual Ranorex.Container AdjustSalt_link
            {
                get
                {
                    return _adjustsalt_linkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AdjustSalt_link item info.
            /// </summary>
            [RepositoryItemInfo("85dfcc15-b4eb-4467-8bc0-a9678d13d250")]
            public virtual RepoItemInfo AdjustSalt_linkInfo
            {
                get
                {
                    return _adjustsalt_linkInfo;
                }
            }

            /// <summary>
            /// The WaterUsageDetails_link item.
            /// </summary>
            [RepositoryItem("d2e5fac0-3e23-43e7-b216-90c940a9f6e5")]
            public virtual Ranorex.Container WaterUsageDetails_link
            {
                get
                {
                    return _waterusagedetails_linkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WaterUsageDetails_link item info.
            /// </summary>
            [RepositoryItemInfo("d2e5fac0-3e23-43e7-b216-90c940a9f6e5")]
            public virtual RepoItemInfo WaterUsageDetails_linkInfo
            {
                get
                {
                    return _waterusagedetails_linkInfo;
                }
            }

            /// <summary>
            /// The RemoveDevice_link item.
            /// </summary>
            [RepositoryItem("12cead18-1b12-466e-90fb-7b064c034f6a")]
            public virtual Ranorex.Container RemoveDevice_link
            {
                get
                {
                    return _removedevice_linkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RemoveDevice_link item info.
            /// </summary>
            [RepositoryItemInfo("12cead18-1b12-466e-90fb-7b064c034f6a")]
            public virtual RepoItemInfo RemoveDevice_linkInfo
            {
                get
                {
                    return _removedevice_linkInfo;
                }
            }

            /// <summary>
            /// The ProductOverview_Header item.
            /// </summary>
            [RepositoryItem("8774d333-7c08-4f86-b261-d94f1c8a1cbf")]
            public virtual Ranorex.Container ProductOverview_Header
            {
                get
                {
                    return _productoverview_headerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ProductOverview_Header item info.
            /// </summary>
            [RepositoryItemInfo("8774d333-7c08-4f86-b261-d94f1c8a1cbf")]
            public virtual RepoItemInfo ProductOverview_HeaderInfo
            {
                get
                {
                    return _productoverview_headerInfo;
                }
            }

            /// <summary>
            /// The ManufacturerPentair_field item.
            /// </summary>
            [RepositoryItem("a01f896b-6954-484b-a1c5-7378743fe52e")]
            public virtual Ranorex.Container ManufacturerPentair_field
            {
                get
                {
                    return _manufacturerpentair_fieldInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ManufacturerPentair_field item info.
            /// </summary>
            [RepositoryItemInfo("a01f896b-6954-484b-a1c5-7378743fe52e")]
            public virtual RepoItemInfo ManufacturerPentair_fieldInfo
            {
                get
                {
                    return _manufacturerpentair_fieldInfo;
                }
            }

            /// <summary>
            /// The DeviceID item.
            /// </summary>
            [RepositoryItem("063180a5-840d-4346-a9b1-7b2dab693c81")]
            public virtual Ranorex.Container DeviceID
            {
                get
                {
                    return _deviceidInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The DeviceID item info.
            /// </summary>
            [RepositoryItemInfo("063180a5-840d-4346-a9b1-7b2dab693c81")]
            public virtual RepoItemInfo DeviceIDInfo
            {
                get
                {
                    return _deviceidInfo;
                }
            }

            /// <summary>
            /// The Model item.
            /// </summary>
            [RepositoryItem("ea9aa73a-7a53-4cbb-8e33-7f0ba0fa9747")]
            public virtual Ranorex.Container Model
            {
                get
                {
                    return _modelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Model item info.
            /// </summary>
            [RepositoryItemInfo("ea9aa73a-7a53-4cbb-8e33-7f0ba0fa9747")]
            public virtual RepoItemInfo ModelInfo
            {
                get
                {
                    return _modelInfo;
                }
            }

            /// <summary>
            /// The ControllerSoftwareVersion item.
            /// </summary>
            [RepositoryItem("299fa8a5-252b-43d4-aaef-75f5a394f0d8")]
            public virtual Ranorex.Container ControllerSoftwareVersion
            {
                get
                {
                    return _controllersoftwareversionInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ControllerSoftwareVersion item info.
            /// </summary>
            [RepositoryItemInfo("299fa8a5-252b-43d4-aaef-75f5a394f0d8")]
            public virtual RepoItemInfo ControllerSoftwareVersionInfo
            {
                get
                {
                    return _controllersoftwareversionInfo;
                }
            }

            /// <summary>
            /// The IoTSoftwareVersion item.
            /// </summary>
            [RepositoryItem("3c8c1d3b-84cf-4ac0-be20-34c81c986956")]
            public virtual Ranorex.Container IoTSoftwareVersion
            {
                get
                {
                    return _iotsoftwareversionInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The IoTSoftwareVersion item info.
            /// </summary>
            [RepositoryItemInfo("3c8c1d3b-84cf-4ac0-be20-34c81c986956")]
            public virtual RepoItemInfo IoTSoftwareVersionInfo
            {
                get
                {
                    return _iotsoftwareversionInfo;
                }
            }

            /// <summary>
            /// The NicknameTestWSAutomation item.
            /// </summary>
            [RepositoryItem("309e3e5c-bf42-4a48-81a8-83ee58c1b3db")]
            public virtual Ranorex.Container NicknameTestWSAutomation
            {
                get
                {
                    return _nicknametestwsautomationInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NicknameTestWSAutomation item info.
            /// </summary>
            [RepositoryItemInfo("309e3e5c-bf42-4a48-81a8-83ee58c1b3db")]
            public virtual RepoItemInfo NicknameTestWSAutomationInfo
            {
                get
                {
                    return _nicknametestwsautomationInfo;
                }
            }

            /// <summary>
            /// The Address item.
            /// </summary>
            [RepositoryItem("b6b33cfa-2d0d-4b60-96c4-ddbcdf0ace68")]
            public virtual Ranorex.Container Address
            {
                get
                {
                    return _addressInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Address item info.
            /// </summary>
            [RepositoryItemInfo("b6b33cfa-2d0d-4b60-96c4-ddbcdf0ace68")]
            public virtual RepoItemInfo AddressInfo
            {
                get
                {
                    return _addressInfo;
                }
            }

            /// <summary>
            /// The BackArrow_PO item.
            /// </summary>
            [RepositoryItem("55a6fd3e-feb0-4d09-972e-ebe1e0cec156")]
            public virtual Ranorex.Container BackArrow_PO
            {
                get
                {
                    return _backarrow_poInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BackArrow_PO item info.
            /// </summary>
            [RepositoryItemInfo("55a6fd3e-feb0-4d09-972e-ebe1e0cec156")]
            public virtual RepoItemInfo BackArrow_POInfo
            {
                get
                {
                    return _backarrow_poInfo;
                }
            }

            /// <summary>
            /// The CheckYourSaltLevel_Header item.
            /// </summary>
            [RepositoryItem("311c773b-f216-4dfa-8ae0-9431a0ddd049")]
            public virtual Ranorex.Container CheckYourSaltLevel_Header
            {
                get
                {
                    return _checkyoursaltlevel_headerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The CheckYourSaltLevel_Header item info.
            /// </summary>
            [RepositoryItemInfo("311c773b-f216-4dfa-8ae0-9431a0ddd049")]
            public virtual RepoItemInfo CheckYourSaltLevel_HeaderInfo
            {
                get
                {
                    return _checkyoursaltlevel_headerInfo;
                }
            }

            /// <summary>
            /// The StaticText_CYSL item.
            /// </summary>
            [RepositoryItem("c88b6d23-e6a7-4264-ad95-c09472c2f6f4")]
            public virtual Ranorex.Container StaticText_CYSL
            {
                get
                {
                    return _statictext_cyslInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The StaticText_CYSL item info.
            /// </summary>
            [RepositoryItemInfo("c88b6d23-e6a7-4264-ad95-c09472c2f6f4")]
            public virtual RepoItemInfo StaticText_CYSLInfo
            {
                get
                {
                    return _statictext_cyslInfo;
                }
            }

            /// <summary>
            /// The NotReadyFor_SaltRefill item.
            /// </summary>
            [RepositoryItem("cd291815-9967-4852-ae0d-054402cfde4f")]
            public virtual Ranorex.Container NotReadyFor_SaltRefill
            {
                get
                {
                    return _notreadyfor_saltrefillInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NotReadyFor_SaltRefill item info.
            /// </summary>
            [RepositoryItemInfo("cd291815-9967-4852-ae0d-054402cfde4f")]
            public virtual RepoItemInfo NotReadyFor_SaltRefillInfo
            {
                get
                {
                    return _notreadyfor_saltrefillInfo;
                }
            }

            /// <summary>
            /// The WaterAboveMySalt item.
            /// </summary>
            [RepositoryItem("d6e11cee-f87f-4513-83bd-725219bb0991")]
            public virtual Ranorex.Container WaterAboveMySalt
            {
                get
                {
                    return _waterabovemysaltInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WaterAboveMySalt item info.
            /// </summary>
            [RepositoryItemInfo("d6e11cee-f87f-4513-83bd-725219bb0991")]
            public virtual RepoItemInfo WaterAboveMySaltInfo
            {
                get
                {
                    return _waterabovemysaltInfo;
                }
            }

            /// <summary>
            /// The OutOfSalt item.
            /// </summary>
            [RepositoryItem("9e3a53b4-82a8-4f9a-ac2a-225670385f4d")]
            public virtual Ranorex.Container OutOfSalt
            {
                get
                {
                    return _outofsaltInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The OutOfSalt item info.
            /// </summary>
            [RepositoryItemInfo("9e3a53b4-82a8-4f9a-ac2a-225670385f4d")]
            public virtual RepoItemInfo OutOfSaltInfo
            {
                get
                {
                    return _outofsaltInfo;
                }
            }

            /// <summary>
            /// The SaltTank item.
            /// </summary>
            [RepositoryItem("0b3a591f-d337-42dc-81fd-097aa1ebc7f5")]
            public virtual Ranorex.Container SaltTank
            {
                get
                {
                    return _salttankInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SaltTank item info.
            /// </summary>
            [RepositoryItemInfo("0b3a591f-d337-42dc-81fd-097aa1ebc7f5")]
            public virtual RepoItemInfo SaltTankInfo
            {
                get
                {
                    return _salttankInfo;
                }
            }

            /// <summary>
            /// The EstimatedSaltLevels_Text item.
            /// </summary>
            [RepositoryItem("bb56f285-cca5-4248-a1ed-aef288049317")]
            public virtual Ranorex.Container EstimatedSaltLevels_Text
            {
                get
                {
                    return _estimatedsaltlevels_textInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The EstimatedSaltLevels_Text item info.
            /// </summary>
            [RepositoryItemInfo("bb56f285-cca5-4248-a1ed-aef288049317")]
            public virtual RepoItemInfo EstimatedSaltLevels_TextInfo
            {
                get
                {
                    return _estimatedsaltlevels_textInfo;
                }
            }

            /// <summary>
            /// The Add_Button item.
            /// </summary>
            [RepositoryItem("86dbb929-8bc7-48ee-a768-b374d531eaba")]
            public virtual Ranorex.Container Add_Button
            {
                get
                {
                    return _add_buttonInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Add_Button item info.
            /// </summary>
            [RepositoryItemInfo("86dbb929-8bc7-48ee-a768-b374d531eaba")]
            public virtual RepoItemInfo Add_ButtonInfo
            {
                get
                {
                    return _add_buttonInfo;
                }
            }

            /// <summary>
            /// The Remove_Button item.
            /// </summary>
            [RepositoryItem("802c7d5e-5986-48c6-90da-94eb3230cee0")]
            public virtual Ranorex.Container Remove_Button
            {
                get
                {
                    return _remove_buttonInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Remove_Button item info.
            /// </summary>
            [RepositoryItemInfo("802c7d5e-5986-48c6-90da-94eb3230cee0")]
            public virtual RepoItemInfo Remove_ButtonInfo
            {
                get
                {
                    return _remove_buttonInfo;
                }
            }

            /// <summary>
            /// The SaltAmount_Field item.
            /// </summary>
            [RepositoryItem("b3a13fe7-6b8a-4843-a7ef-42b581230787")]
            public virtual Ranorex.Container SaltAmount_Field
            {
                get
                {
                    return _saltamount_fieldInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SaltAmount_Field item info.
            /// </summary>
            [RepositoryItemInfo("b3a13fe7-6b8a-4843-a7ef-42b581230787")]
            public virtual RepoItemInfo SaltAmount_FieldInfo
            {
                get
                {
                    return _saltamount_fieldInfo;
                }
            }

            /// <summary>
            /// The ADJUSTSALT_button item.
            /// </summary>
            [RepositoryItem("51eb93fc-7693-4100-8ffc-c33306b708f1")]
            public virtual Ranorex.Container ADJUSTSALT_button
            {
                get
                {
                    return _adjustsalt_buttonInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ADJUSTSALT_button item info.
            /// </summary>
            [RepositoryItemInfo("51eb93fc-7693-4100-8ffc-c33306b708f1")]
            public virtual RepoItemInfo ADJUSTSALT_buttonInfo
            {
                get
                {
                    return _adjustsalt_buttonInfo;
                }
            }

            /// <summary>
            /// The AdjustSaltConfirmation item.
            /// </summary>
            [RepositoryItem("f4ba9c06-8a92-4d53-b836-7d06026891c4")]
            public virtual Ranorex.Container AdjustSaltConfirmation
            {
                get
                {
                    return _adjustsaltconfirmationInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AdjustSaltConfirmation item info.
            /// </summary>
            [RepositoryItemInfo("f4ba9c06-8a92-4d53-b836-7d06026891c4")]
            public virtual RepoItemInfo AdjustSaltConfirmationInfo
            {
                get
                {
                    return _adjustsaltconfirmationInfo;
                }
            }

            /// <summary>
            /// The CANCEL item.
            /// </summary>
            [RepositoryItem("cb892f95-79b8-4893-b256-c1c8b32568bf")]
            public virtual Ranorex.Container CANCEL
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The CANCEL item info.
            /// </summary>
            [RepositoryItemInfo("cb892f95-79b8-4893-b256-c1c8b32568bf")]
            public virtual RepoItemInfo CANCELInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The CONFIRM item.
            /// </summary>
            [RepositoryItem("a439e746-5255-4d31-8698-14d29e998f9e")]
            public virtual Ranorex.Container CONFIRM
            {
                get
                {
                    return _confirmInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The CONFIRM item info.
            /// </summary>
            [RepositoryItemInfo("a439e746-5255-4d31-8698-14d29e998f9e")]
            public virtual RepoItemInfo CONFIRMInfo
            {
                get
                {
                    return _confirmInfo;
                }
            }

            /// <summary>
            /// The SaltAdded item.
            /// </summary>
            [RepositoryItem("2a1813f5-70d3-4063-b90d-20d4342c1ed7")]
            public virtual Ranorex.Container SaltAdded
            {
                get
                {
                    return _saltaddedInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SaltAdded item info.
            /// </summary>
            [RepositoryItemInfo("2a1813f5-70d3-4063-b90d-20d4342c1ed7")]
            public virtual RepoItemInfo SaltAddedInfo
            {
                get
                {
                    return _saltaddedInfo;
                }
            }

            /// <summary>
            /// The CONTINUE item.
            /// </summary>
            [RepositoryItem("604c22ac-4d07-4fd7-8b62-72d4f83b5bb7")]
            public virtual Ranorex.Container CONTINUE
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The CONTINUE item info.
            /// </summary>
            [RepositoryItemInfo("604c22ac-4d07-4fd7-8b62-72d4f83b5bb7")]
            public virtual RepoItemInfo CONTINUEInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The AdjustSaltHeader item.
            /// </summary>
            [RepositoryItem("aec00056-027a-4f59-b9d3-b0ed61ed3670")]
            public virtual Ranorex.Container AdjustSaltHeader
            {
                get
                {
                    return _adjustsaltheaderInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AdjustSaltHeader item info.
            /// </summary>
            [RepositoryItemInfo("aec00056-027a-4f59-b9d3-b0ed61ed3670")]
            public virtual RepoItemInfo AdjustSaltHeaderInfo
            {
                get
                {
                    return _adjustsaltheaderInfo;
                }
            }

            /// <summary>
            /// The Date_Field item.
            /// </summary>
            [RepositoryItem("0c668032-4fa5-4935-988e-ee09a789aae1")]
            public virtual Ranorex.Container Date_Field
            {
                get
                {
                    return _date_fieldInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Date_Field item info.
            /// </summary>
            [RepositoryItemInfo("0c668032-4fa5-4935-988e-ee09a789aae1")]
            public virtual RepoItemInfo Date_FieldInfo
            {
                get
                {
                    return _date_fieldInfo;
                }
            }

            /// <summary>
            /// The Notifications_Header item.
            /// </summary>
            [RepositoryItem("200b855a-eead-4db0-872b-41df242db261")]
            public virtual Ranorex.Container Notifications_Header
            {
                get
                {
                    return _notifications_headerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Notifications_Header item info.
            /// </summary>
            [RepositoryItemInfo("200b855a-eead-4db0-872b-41df242db261")]
            public virtual RepoItemInfo Notifications_HeaderInfo
            {
                get
                {
                    return _notifications_headerInfo;
                }
            }

            /// <summary>
            /// The AllNotifications item.
            /// </summary>
            [RepositoryItem("bcbdd62e-92cf-4669-a637-3656f6495805")]
            public virtual Ranorex.Container AllNotifications
            {
                get
                {
                    return _allnotificationsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AllNotifications item info.
            /// </summary>
            [RepositoryItemInfo("bcbdd62e-92cf-4669-a637-3656f6495805")]
            public virtual RepoItemInfo AllNotificationsInfo
            {
                get
                {
                    return _allnotificationsInfo;
                }
            }

            /// <summary>
            /// The Toggle_All item.
            /// </summary>
            [RepositoryItem("f4806dc7-3f45-474c-825b-be08822413e4")]
            public virtual Ranorex.Container Toggle_All
            {
                get
                {
                    return _toggle_allInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Toggle_All item info.
            /// </summary>
            [RepositoryItemInfo("f4806dc7-3f45-474c-825b-be08822413e4")]
            public virtual RepoItemInfo Toggle_AllInfo
            {
                get
                {
                    return _toggle_allInfo;
                }
            }

            /// <summary>
            /// The Backarrow_Notifications item.
            /// </summary>
            [RepositoryItem("b824ec7f-9c26-4370-8bef-25a2568b4981")]
            public virtual Ranorex.Container Backarrow_Notifications
            {
                get
                {
                    return _backarrow_notificationsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Backarrow_Notifications item info.
            /// </summary>
            [RepositoryItemInfo("b824ec7f-9c26-4370-8bef-25a2568b4981")]
            public virtual RepoItemInfo Backarrow_NotificationsInfo
            {
                get
                {
                    return _backarrow_notificationsInfo;
                }
            }

            /// <summary>
            /// The ProductSupport_Header item.
            /// </summary>
            [RepositoryItem("dbcad9a9-1f96-4736-b393-207654c1ce30")]
            public virtual Ranorex.Container ProductSupport_Header
            {
                get
                {
                    return _productsupport_headerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ProductSupport_Header item info.
            /// </summary>
            [RepositoryItemInfo("dbcad9a9-1f96-4736-b393-207654c1ce30")]
            public virtual RepoItemInfo ProductSupport_HeaderInfo
            {
                get
                {
                    return _productsupport_headerInfo;
                }
            }

            /// <summary>
            /// The ConnectedSoftenerSupport item.
            /// </summary>
            [RepositoryItem("b7fa124e-06f1-4eb5-bb00-2d08ef43c45a")]
            public virtual Ranorex.H2Tag ConnectedSoftenerSupport
            {
                get
                {
                    return _connectedsoftenersupportInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The ConnectedSoftenerSupport item info.
            /// </summary>
            [RepositoryItemInfo("b7fa124e-06f1-4eb5-bb00-2d08ef43c45a")]
            public virtual RepoItemInfo ConnectedSoftenerSupportInfo
            {
                get
                {
                    return _connectedsoftenersupportInfo;
                }
            }

            /// <summary>
            /// The backArrow_PS item.
            /// </summary>
            [RepositoryItem("76fbc474-4f96-46fc-b5c3-ebebfbdd5b25")]
            public virtual Ranorex.Container backArrow_PS
            {
                get
                {
                    return _backarrow_psInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The backArrow_PS item info.
            /// </summary>
            [RepositoryItemInfo("76fbc474-4f96-46fc-b5c3-ebebfbdd5b25")]
            public virtual RepoItemInfo backArrow_PSInfo
            {
                get
                {
                    return _backarrow_psInfo;
                }
            }

            /// <summary>
            /// The WiFi_Header item.
            /// </summary>
            [RepositoryItem("3280c09b-59b0-4e86-8c58-32f428c62c8d")]
            public virtual Ranorex.Container WiFi_Header
            {
                get
                {
                    return _wifi_headerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WiFi_Header item info.
            /// </summary>
            [RepositoryItemInfo("3280c09b-59b0-4e86-8c58-32f428c62c8d")]
            public virtual RepoItemInfo WiFi_HeaderInfo
            {
                get
                {
                    return _wifi_headerInfo;
                }
            }

            /// <summary>
            /// The NetworkName item.
            /// </summary>
            [RepositoryItem("42597f4c-8345-4f12-b9cf-85130bda6340")]
            public virtual Ranorex.Container NetworkName
            {
                get
                {
                    return _networknameInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NetworkName item info.
            /// </summary>
            [RepositoryItemInfo("42597f4c-8345-4f12-b9cf-85130bda6340")]
            public virtual RepoItemInfo NetworkNameInfo
            {
                get
                {
                    return _networknameInfo;
                }
            }

            /// <summary>
            /// The SignalStrength item.
            /// </summary>
            [RepositoryItem("c804621c-b115-42dd-ae52-faac2f21098b")]
            public virtual Ranorex.Container SignalStrength
            {
                get
                {
                    return _signalstrengthInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SignalStrength item info.
            /// </summary>
            [RepositoryItemInfo("c804621c-b115-42dd-ae52-faac2f21098b")]
            public virtual RepoItemInfo SignalStrengthInfo
            {
                get
                {
                    return _signalstrengthInfo;
                }
            }

            /// <summary>
            /// The ChangeWiFiNetwork item.
            /// </summary>
            [RepositoryItem("2ce730b0-085a-4964-8ada-40e1cf54d121")]
            public virtual Ranorex.Container ChangeWiFiNetwork
            {
                get
                {
                    return _changewifinetworkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ChangeWiFiNetwork item info.
            /// </summary>
            [RepositoryItemInfo("2ce730b0-085a-4964-8ada-40e1cf54d121")]
            public virtual RepoItemInfo ChangeWiFiNetworkInfo
            {
                get
                {
                    return _changewifinetworkInfo;
                }
            }

            /// <summary>
            /// The BluetoothPairingScreen item.
            /// </summary>
            [RepositoryItem("976b6d0e-a5f5-4345-bc91-0ee11223162f")]
            public virtual Ranorex.Container BluetoothPairingScreen
            {
                get
                {
                    return _bluetoothpairingscreenInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BluetoothPairingScreen item info.
            /// </summary>
            [RepositoryItemInfo("976b6d0e-a5f5-4345-bc91-0ee11223162f")]
            public virtual RepoItemInfo BluetoothPairingScreenInfo
            {
                get
                {
                    return _bluetoothpairingscreenInfo;
                }
            }

            /// <summary>
            /// The BackArrow_BTPair item.
            /// </summary>
            [RepositoryItem("93895b2d-d744-4ddf-b606-7efaf29023c7")]
            public virtual Ranorex.Container BackArrow_BTPair
            {
                get
                {
                    return _backarrow_btpairInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BackArrow_BTPair item info.
            /// </summary>
            [RepositoryItemInfo("93895b2d-d744-4ddf-b606-7efaf29023c7")]
            public virtual RepoItemInfo BackArrow_BTPairInfo
            {
                get
                {
                    return _backarrow_btpairInfo;
                }
            }

            /// <summary>
            /// The BackArrow_WiFi item.
            /// </summary>
            [RepositoryItem("883be278-0007-4d6f-aec2-670cf43f28f2")]
            public virtual Ranorex.Container BackArrow_WiFi
            {
                get
                {
                    return _backarrow_wifiInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BackArrow_WiFi item info.
            /// </summary>
            [RepositoryItemInfo("883be278-0007-4d6f-aec2-670cf43f28f2")]
            public virtual RepoItemInfo BackArrow_WiFiInfo
            {
                get
                {
                    return _backarrow_wifiInfo;
                }
            }

            /// <summary>
            /// The Water_UsageDays_count item.
            /// </summary>
            [RepositoryItem("f2890560-ae72-4392-b4cc-0c814f99f819")]
            public virtual Ranorex.Container Water_UsageDays_count
            {
                get
                {
                    return _water_usagedays_countInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Water_UsageDays_count item info.
            /// </summary>
            [RepositoryItemInfo("f2890560-ae72-4392-b4cc-0c814f99f819")]
            public virtual RepoItemInfo Water_UsageDays_countInfo
            {
                get
                {
                    return _water_usagedays_countInfo;
                }
            }

            /// <summary>
            /// The WS_deviceList item.
            /// </summary>
            [RepositoryItem("2fba6e87-9225-406b-97ac-f59911b9cc2d")]
            public virtual Ranorex.Container WS_deviceList
            {
                get
                {
                    return _ws_devicelistInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WS_deviceList item info.
            /// </summary>
            [RepositoryItemInfo("2fba6e87-9225-406b-97ac-f59911b9cc2d")]
            public virtual RepoItemInfo WS_deviceListInfo
            {
                get
                {
                    return _ws_devicelistInfo;
                }
            }

            /// <summary>
            /// The Account_Header item.
            /// </summary>
            [RepositoryItem("cd7cb1a7-c3d8-4026-8094-bb8201e2de53")]
            public virtual Ranorex.Container Account_Header
            {
                get
                {
                    return _account_headerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Account_Header item info.
            /// </summary>
            [RepositoryItemInfo("cd7cb1a7-c3d8-4026-8094-bb8201e2de53")]
            public virtual RepoItemInfo Account_HeaderInfo
            {
                get
                {
                    return _account_headerInfo;
                }
            }

            /// <summary>
            /// The AccountsTab item.
            /// </summary>
            [RepositoryItem("65ef31ec-709d-4a12-a52c-c8a129142938")]
            public virtual Ranorex.Container AccountsTab
            {
                get
                {
                    return _accountstabInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AccountsTab item info.
            /// </summary>
            [RepositoryItemInfo("65ef31ec-709d-4a12-a52c-c8a129142938")]
            public virtual RepoItemInfo AccountsTabInfo
            {
                get
                {
                    return _accountstabInfo;
                }
            }

            /// <summary>
            /// The LogOutlink item.
            /// </summary>
            [RepositoryItem("06136611-3384-4857-9593-6f8144f99685")]
            public virtual Ranorex.Container LogOutlink
            {
                get
                {
                    return _logoutlinkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The LogOutlink item info.
            /// </summary>
            [RepositoryItemInfo("06136611-3384-4857-9593-6f8144f99685")]
            public virtual RepoItemInfo LogOutlinkInfo
            {
                get
                {
                    return _logoutlinkInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("e2439326-43e2-487e-8fa1-8762c2b13ee0")]
            public virtual Ranorex.Container LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("e2439326-43e2-487e-8fa1-8762c2b13ee0")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The SwipeLeft1 item.
            /// </summary>
            [RepositoryItem("3869091b-9042-49f3-aac5-2819e5f5578d")]
            public virtual Ranorex.Container SwipeLeft1
            {
                get
                {
                    return _swipeleft1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SwipeLeft1 item info.
            /// </summary>
            [RepositoryItemInfo("3869091b-9042-49f3-aac5-2819e5f5578d")]
            public virtual RepoItemInfo SwipeLeft1Info
            {
                get
                {
                    return _swipeleft1Info;
                }
            }

            /// <summary>
            /// The SwipeLeft2 item.
            /// </summary>
            [RepositoryItem("2c965b51-04b3-4e75-9e4a-03114a74a05d")]
            public virtual Ranorex.Container SwipeLeft2
            {
                get
                {
                    return _swipeleft2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SwipeLeft2 item info.
            /// </summary>
            [RepositoryItemInfo("2c965b51-04b3-4e75-9e4a-03114a74a05d")]
            public virtual RepoItemInfo SwipeLeft2Info
            {
                get
                {
                    return _swipeleft2Info;
                }
            }

            /// <summary>
            /// The SwipeLeft3 item.
            /// </summary>
            [RepositoryItem("3dc32ceb-e1d4-4362-b909-c1153210ca7e")]
            public virtual Ranorex.Container SwipeLeft3
            {
                get
                {
                    return _swipeleft3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SwipeLeft3 item info.
            /// </summary>
            [RepositoryItemInfo("3dc32ceb-e1d4-4362-b909-c1153210ca7e")]
            public virtual RepoItemInfo SwipeLeft3Info
            {
                get
                {
                    return _swipeleft3Info;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("2730181c-3ad2-46dd-ae4e-380c60a93dbc")]
            public virtual Ranorex.Container NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("2730181c-3ad2-46dd-ae4e-380c60a93dbc")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
