///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The login recording.
    /// </summary>
    [TestModule("34e33e57-18bf-40ba-9f0c-eddaa22e5e0f", ModuleType.Recording, 1)]
    public partial class login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the iOS_WS_TestRepository repository.
        /// </summary>
        public static iOS_WS_TestRepository repo = iOS_WS_TestRepository.Instance;

        static login instance = new login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public login()
        {
            EmailID = "tanmay.anand@happiestminds.com";
            Password = "Password@123";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static login Instance
        {
            get { return instance; }
        }

#region Variables

        string _EmailID;

        /// <summary>
        /// Gets or sets the value of variable EmailID.
        /// </summary>
        [TestVariable("86e7b064-789c-40ae-9745-a683ad5d2cbe")]
        public string EmailID
        {
            get { return _EmailID; }
            set { _EmailID = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("b4f8d97c-2aca-458c-ad4e-72bef042bf6c")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$EmailID' on item 'ComPentairPentairhome.Login_Field'.", repo.ComPentairPentairhome.Login_FieldInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.Login_Field.Element.SetAttributeValue("Text", EmailID);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(2));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Password' on item 'ComPentairPentairhome.Password_Field'.", repo.ComPentairPentairhome.Password_FieldInfo, new RecordItemIndex(3));
            repo.ComPentairPentairhome.Password_Field.Element.SetAttributeValue("Text", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(4));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.LOGIN_Btn' at Center", repo.ComPentairPentairhome.LOGIN_BtnInfo, new RecordItemIndex(5));
            repo.ComPentairPentairhome.LOGIN_Btn.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 20s.", new RecordItemIndex(6));
            Delay.Duration(20000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ComPentairPentairhome.AddDevice_HomeDasboard'", repo.ComPentairPentairhome.AddDevice_HomeDasboardInfo, new ActionTimeout(10000), new RecordItemIndex(7));
            repo.ComPentairPentairhome.AddDevice_HomeDasboardInfo.WaitForExists(10000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
