///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyProductSupport recording.
    /// </summary>
    [TestModule("020783dd-44f2-4498-817b-3e7293f6bb31", ModuleType.Recording, 1)]
    public partial class VerifyProductSupport : ITestModule
    {
        /// <summary>
        /// Holds an instance of the iOS_WS_TestRepository repository.
        /// </summary>
        public static iOS_WS_TestRepository repo = iOS_WS_TestRepository.Instance;

        static VerifyProductSupport instance = new VerifyProductSupport();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyProductSupport()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyProductSupport Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ProductSupport_link' at Center", repo.ProductSupport_linkInfo, new RecordItemIndex(1));
            repo.ProductSupport_link.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(2));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.ProductSupport_Header'.", repo.ComPentairPentairhome.ProductSupport_HeaderInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ComPentairPentairhome.ProductSupport_HeaderInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>'Product Support') on item 'ComPentairPentairhome.ProductSupport_Header'.", repo.ComPentairPentairhome.ProductSupport_HeaderInfo, new RecordItemIndex(4));
            Validate.AttributeContains(repo.ComPentairPentairhome.ProductSupport_HeaderInfo, "AccessibilityLabel", "Product Support");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.ConnectedSoftenerSupport'.", repo.ComPentairPentairhome.ConnectedSoftenerSupportInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ComPentairPentairhome.ConnectedSoftenerSupportInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Connected Softener Support') on item 'ComPentairPentairhome.ConnectedSoftenerSupport'.", repo.ComPentairPentairhome.ConnectedSoftenerSupportInfo, new RecordItemIndex(7));
            Validate.AttributeContains(repo.ComPentairPentairhome.ConnectedSoftenerSupportInfo, "InnerText", "Connected Softener Support");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.backArrow_PS' at Center", repo.ComPentairPentairhome.backArrow_PSInfo, new RecordItemIndex(9));
            repo.ComPentairPentairhome.backArrow_PS.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(10));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
