///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_Adjust_Salt_01 recording.
    /// </summary>
    [TestModule("4ec74746-36d6-4487-a61b-88c088e14bb6", ModuleType.Recording, 1)]
    public partial class Verify_Adjust_Salt_01 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the iOS_WS_TestRepository repository.
        /// </summary>
        public static iOS_WS_TestRepository repo = iOS_WS_TestRepository.Instance;

        static Verify_Adjust_Salt_01 instance = new Verify_Adjust_Salt_01();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_Adjust_Salt_01()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_Adjust_Salt_01 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AdjustSalt_link' at Center", repo.ComPentairPentairhome.AdjustSalt_linkInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.AdjustSalt_link.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.CheckYourSaltLevel_Header'.", repo.ComPentairPentairhome.CheckYourSaltLevel_HeaderInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ComPentairPentairhome.CheckYourSaltLevel_HeaderInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>'Check Your Salt Level') on item 'ComPentairPentairhome.CheckYourSaltLevel_Header'.", repo.ComPentairPentairhome.CheckYourSaltLevel_HeaderInfo, new RecordItemIndex(4));
            Validate.AttributeContains(repo.ComPentairPentairhome.CheckYourSaltLevel_HeaderInfo, "AccessibilityLabel", "Check Your Salt Level");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.StaticText_CYSL'.", repo.ComPentairPentairhome.StaticText_CYSLInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ComPentairPentairhome.StaticText_CYSLInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>'Before adding salt, please check your brine tank and indicate the salt level:') on item 'ComPentairPentairhome.StaticText_CYSL'.", repo.ComPentairPentairhome.StaticText_CYSLInfo, new RecordItemIndex(6));
            Validate.AttributeContains(repo.ComPentairPentairhome.StaticText_CYSLInfo, "AccessibilityLabel", "Before adding salt, please check your brine tank and indicate the salt level:");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.NotReadyFor_SaltRefill'.", repo.ComPentairPentairhome.NotReadyFor_SaltRefillInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ComPentairPentairhome.NotReadyFor_SaltRefillInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>'I’m not ready for a salt refill.') on item 'ComPentairPentairhome.NotReadyFor_SaltRefill'.", repo.ComPentairPentairhome.NotReadyFor_SaltRefillInfo, new RecordItemIndex(8));
            Validate.AttributeContains(repo.ComPentairPentairhome.NotReadyFor_SaltRefillInfo, "AccessibilityLabel", "I’m not ready for a salt refill.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(9));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.WaterAboveMySalt'.", repo.ComPentairPentairhome.WaterAboveMySaltInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ComPentairPentairhome.WaterAboveMySaltInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>'I can see water above my salt.') on item 'ComPentairPentairhome.WaterAboveMySalt'.", repo.ComPentairPentairhome.WaterAboveMySaltInfo, new RecordItemIndex(11));
            Validate.AttributeContains(repo.ComPentairPentairhome.WaterAboveMySaltInfo, "AccessibilityLabel", "I can see water above my salt.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(12));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.OutOfSalt'.", repo.ComPentairPentairhome.OutOfSaltInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ComPentairPentairhome.OutOfSaltInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'ComPentairPentairhome.OutOfSalt'.", repo.ComPentairPentairhome.OutOfSaltInfo, new RecordItemIndex(14));
            Validate.AttributeContains(repo.ComPentairPentairhome.OutOfSaltInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(15));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.NotReadyFor_SaltRefill' at Center", repo.ComPentairPentairhome.NotReadyFor_SaltRefillInfo, new RecordItemIndex(16));
            repo.ComPentairPentairhome.NotReadyFor_SaltRefill.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(17));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
