///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyRemoveSalt recording.
    /// </summary>
    [TestModule("402f11b4-b966-4695-95cb-da08b8f44140", ModuleType.Recording, 1)]
    public partial class VerifyRemoveSalt : ITestModule
    {
        /// <summary>
        /// Holds an instance of the iOS_WS_TestRepository repository.
        /// </summary>
        public static iOS_WS_TestRepository repo = iOS_WS_TestRepository.Instance;

        static VerifyRemoveSalt instance = new VerifyRemoveSalt();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyRemoveSalt()
        {
            SaltRemoved = "100";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyRemoveSalt Instance
        {
            get { return instance; }
        }

#region Variables

        string _SaltRemoved;

        /// <summary>
        /// Gets or sets the value of variable SaltRemoved.
        /// </summary>
        [TestVariable("52f6c5bd-ae0e-40d8-a2c7-b260def7eaa5")]
        public string SaltRemoved
        {
            get { return _SaltRemoved; }
            set { _SaltRemoved = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AdjustSalt_link' at Center", repo.ComPentairPentairhome.AdjustSalt_linkInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.AdjustSalt_link.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.NotReadyFor_SaltRefill' at Center", repo.ComPentairPentairhome.NotReadyFor_SaltRefillInfo, new RecordItemIndex(3));
            repo.ComPentairPentairhome.NotReadyFor_SaltRefill.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(4));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.AdjustSaltHeader'.", repo.ComPentairPentairhome.AdjustSaltHeaderInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ComPentairPentairhome.AdjustSaltHeaderInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.SaltAmount_Field' at Center", repo.ComPentairPentairhome.SaltAmount_FieldInfo, new RecordItemIndex(6));
            repo.ComPentairPentairhome.SaltAmount_Field.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Salt removed to '100' on item 'ComPentairPentairhome.SaltAmount_Field'.", repo.ComPentairPentairhome.SaltAmount_FieldInfo, new RecordItemIndex(8));
            repo.ComPentairPentairhome.SaltAmount_Field.Element.SetAttributeValue("Salt removed", "100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(9));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Remove_Button' at Center", repo.ComPentairPentairhome.Remove_ButtonInfo, new RecordItemIndex(10));
            repo.ComPentairPentairhome.Remove_Button.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(11));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ADJUSTSALT_button' at Center", repo.ComPentairPentairhome.ADJUSTSALT_buttonInfo, new RecordItemIndex(12));
            repo.ComPentairPentairhome.ADJUSTSALT_button.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(13));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.CONFIRM' at Center", repo.ComPentairPentairhome.CONFIRMInfo, new RecordItemIndex(14));
            repo.ComPentairPentairhome.CONFIRM.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(15));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.CONTINUE' at Center", repo.ComPentairPentairhome.CONTINUEInfo, new RecordItemIndex(16));
            repo.ComPentairPentairhome.CONTINUE.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(17));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
