///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyWS_Settings recording.
    /// </summary>
    [TestModule("d0438b63-e399-4765-95bf-3b2a1e4882e8", ModuleType.Recording, 1)]
    public partial class VerifyWS_Settings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the iOS_WS_TestRepository repository.
        /// </summary>
        public static iOS_WS_TestRepository repo = iOS_WS_TestRepository.Instance;

        static VerifyWS_Settings instance = new VerifyWS_Settings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyWS_Settings()
        {
            NickName = "Test WS Automation";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyWS_Settings Instance
        {
            get { return instance; }
        }

#region Variables

        string _NickName;

        /// <summary>
        /// Gets or sets the value of variable NickName.
        /// </summary>
        [TestVariable("32f68053-e942-4da2-8320-307d433dc154")]
        public string NickName
        {
            get { return _NickName; }
            set { _NickName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.WS_icon'.", repo.ComPentairPentairhome.WS_iconInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ComPentairPentairhome.WS_iconInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.ProductOverview_Link'.", repo.ComPentairPentairhome.ProductOverview_LinkInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ComPentairPentairhome.ProductOverview_LinkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Product Overview') on item 'ComPentairPentairhome.ProductOverview_Link'.", repo.ComPentairPentairhome.ProductOverview_LinkInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ComPentairPentairhome.ProductOverview_LinkInfo, "AccessibilityLabel", "Product Overview");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.NickName_Prod_Setting'.", repo.ComPentairPentairhome.NickName_Prod_SettingInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ComPentairPentairhome.NickName_Prod_SettingInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>$NickName) on item 'ComPentairPentairhome.NickName_Prod_Setting'.", repo.ComPentairPentairhome.NickName_Prod_SettingInfo, new RecordItemIndex(7));
            Validate.AttributeContains(repo.ComPentairPentairhome.NickName_Prod_SettingInfo, "AccessibilityLabel", NickName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.Notifications_link'.", repo.ComPentairPentairhome.Notifications_linkInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ComPentairPentairhome.Notifications_linkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Notifications') on item 'ComPentairPentairhome.Notifications_link'.", repo.ComPentairPentairhome.Notifications_linkInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ComPentairPentairhome.Notifications_linkInfo, "AccessibilityLabel", "Notifications");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(11));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ProductSupport_link'.", repo.ProductSupport_linkInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ProductSupport_linkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Product Support') on item 'ProductSupport_link'.", repo.ProductSupport_linkInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ProductSupport_linkInfo, "AccessibilityLabel", "Product Support");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(14));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
