///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_Add_Salt recording.
    /// </summary>
    [TestModule("02ee0714-6b35-4efd-9f46-c79a5b070eb8", ModuleType.Recording, 1)]
    public partial class Verify_Add_Salt : ITestModule
    {
        /// <summary>
        /// Holds an instance of the iOS_WS_TestRepository repository.
        /// </summary>
        public static iOS_WS_TestRepository repo = iOS_WS_TestRepository.Instance;

        static Verify_Add_Salt instance = new Verify_Add_Salt();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_Add_Salt()
        {
            SaltAmount = "100";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_Add_Salt Instance
        {
            get { return instance; }
        }

#region Variables

        string _SaltAmount;

        /// <summary>
        /// Gets or sets the value of variable SaltAmount.
        /// </summary>
        [TestVariable("b6c4c08a-f4fe-4a2b-9607-2571da9bc8aa")]
        public string SaltAmount
        {
            get { return _SaltAmount; }
            set { _SaltAmount = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            // Salt Added
            Report.Log(ReportLevel.Info, "Set value", "Salt Added\r\nSetting attribute Salt Added to '$SaltAmount' on item 'ComPentairPentairhome.SaltAmount_Field'.", repo.ComPentairPentairhome.SaltAmount_FieldInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.SaltAmount_Field.Element.SetAttributeValue("Salt Added", SaltAmount);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ADJUSTSALT_button' at Center", repo.ComPentairPentairhome.ADJUSTSALT_buttonInfo, new RecordItemIndex(3));
            repo.ComPentairPentairhome.ADJUSTSALT_button.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.AdjustSaltConfirmation'.", repo.ComPentairPentairhome.AdjustSaltConfirmationInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ComPentairPentairhome.AdjustSaltConfirmationInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Adjust Salt Confirmation') on item 'ComPentairPentairhome.AdjustSaltConfirmation'.", repo.ComPentairPentairhome.AdjustSaltConfirmationInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ComPentairPentairhome.AdjustSaltConfirmationInfo, "AccessibilityLabel", "Adjust Salt Confirmation");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.CANCEL' at Center", repo.ComPentairPentairhome.CANCELInfo, new RecordItemIndex(7));
            repo.ComPentairPentairhome.CANCEL.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.CONFIRM' at Center", repo.ComPentairPentairhome.CONFIRMInfo, new RecordItemIndex(9));
            repo.ComPentairPentairhome.CONFIRM.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(10));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>'Salt Added') on item 'ComPentairPentairhome.SaltAdded'.", repo.ComPentairPentairhome.SaltAddedInfo, new RecordItemIndex(11));
            Validate.AttributeContains(repo.ComPentairPentairhome.SaltAddedInfo, "AccessibilityLabel", "Salt Added");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.CONTINUE' at Center", repo.ComPentairPentairhome.CONTINUEInfo, new RecordItemIndex(12));
            repo.ComPentairPentairhome.CONTINUE.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(13));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
