///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyWS_Setting_02 recording.
    /// </summary>
    [TestModule("282342dc-78ea-460a-9bb5-55527bb02418", ModuleType.Recording, 1)]
    public partial class VerifyWS_Setting_02 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the iOS_WS_TestRepository repository.
        /// </summary>
        public static iOS_WS_TestRepository repo = iOS_WS_TestRepository.Instance;

        static VerifyWS_Setting_02 instance = new VerifyWS_Setting_02();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyWS_Setting_02()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyWS_Setting_02 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Remote Monitoring') on item 'ComPentairPentairhome.RemoteMonitoring_Link'.", repo.ComPentairPentairhome.RemoteMonitoring_LinkInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ComPentairPentairhome.RemoteMonitoring_LinkInfo, "AccessibilityLabel", "Remote Monitoring");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.RemoteMonitoring_Link'.", repo.ComPentairPentairhome.RemoteMonitoring_LinkInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ComPentairPentairhome.RemoteMonitoring_LinkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Contact a Professional') on item 'ComPentairPentairhome.ContactAProfessional_link'.", repo.ComPentairPentairhome.ContactAProfessional_linkInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ComPentairPentairhome.ContactAProfessional_linkInfo, "AccessibilityLabel", "Contact a Professional");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.ContactAProfessional_link'.", repo.ComPentairPentairhome.ContactAProfessional_linkInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ComPentairPentairhome.ContactAProfessional_linkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(6));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='WiFi') on item 'ComPentairPentairhome.WiFi_link'.", repo.ComPentairPentairhome.WiFi_linkInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ComPentairPentairhome.WiFi_linkInfo, "AccessibilityLabel", "WiFi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.WiFi_link'.", repo.ComPentairPentairhome.WiFi_linkInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ComPentairPentairhome.WiFi_linkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(9));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Adjust Salt') on item 'ComPentairPentairhome.AdjustSalt_link'.", repo.ComPentairPentairhome.AdjustSalt_linkInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ComPentairPentairhome.AdjustSalt_linkInfo, "AccessibilityLabel", "Adjust Salt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.AdjustSalt_link'.", repo.ComPentairPentairhome.AdjustSalt_linkInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ComPentairPentairhome.AdjustSalt_linkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(12));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Water Usage Details') on item 'ComPentairPentairhome.WaterUsageDetails_link'.", repo.ComPentairPentairhome.WaterUsageDetails_linkInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ComPentairPentairhome.WaterUsageDetails_linkInfo, "AccessibilityLabel", "Water Usage Details");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.WaterUsageDetails_link'.", repo.ComPentairPentairhome.WaterUsageDetails_linkInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.ComPentairPentairhome.WaterUsageDetails_linkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(15));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibilityLabel='Remove Device') on item 'ComPentairPentairhome.RemoveDevice_link'.", repo.ComPentairPentairhome.RemoveDevice_linkInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.ComPentairPentairhome.RemoveDevice_linkInfo, "AccessibilityLabel", "Remove Device");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.RemoveDevice_link'.", repo.ComPentairPentairhome.RemoveDevice_linkInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.ComPentairPentairhome.RemoveDevice_linkInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(18));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
