///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace iOS_WS_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_AdjustSalt_Screen recording.
    /// </summary>
    [TestModule("de32bb8e-f98e-4bb3-b227-532b8951f02e", ModuleType.Recording, 1)]
    public partial class Verify_AdjustSalt_Screen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the iOS_WS_TestRepository repository.
        /// </summary>
        public static iOS_WS_TestRepository repo = iOS_WS_TestRepository.Instance;

        static Verify_AdjustSalt_Screen instance = new Verify_AdjustSalt_Screen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_AdjustSalt_Screen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_AdjustSalt_Screen Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.AdjustSaltHeader'.", repo.ComPentairPentairhome.AdjustSaltHeaderInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ComPentairPentairhome.AdjustSaltHeaderInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.SaltTank'.", repo.ComPentairPentairhome.SaltTankInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ComPentairPentairhome.SaltTankInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>'Adjust Salt') on item 'ComPentairPentairhome.AdjustSaltHeader'.", repo.ComPentairPentairhome.AdjustSaltHeaderInfo, new RecordItemIndex(3));
            Validate.AttributeContains(repo.ComPentairPentairhome.AdjustSaltHeaderInfo, "AccessibilityLabel", "Adjust Salt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.EstimatedSaltLevels_Text'.", repo.ComPentairPentairhome.EstimatedSaltLevels_TextInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ComPentairPentairhome.EstimatedSaltLevels_TextInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (AccessibilityLabel>'Estimated Salt Levels') on item 'ComPentairPentairhome.EstimatedSaltLevels_Text'.", repo.ComPentairPentairhome.EstimatedSaltLevels_TextInfo, new RecordItemIndex(5));
            Validate.AttributeContains(repo.ComPentairPentairhome.EstimatedSaltLevels_TextInfo, "AccessibilityLabel", "Estimated Salt Levels");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.Add_Button'.", repo.ComPentairPentairhome.Add_ButtonInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ComPentairPentairhome.Add_ButtonInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.Add_Button'.", repo.ComPentairPentairhome.Add_ButtonInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ComPentairPentairhome.Add_ButtonInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.Remove_Button'.", repo.ComPentairPentairhome.Remove_ButtonInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ComPentairPentairhome.Remove_ButtonInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.Remove_Button'.", repo.ComPentairPentairhome.Remove_ButtonInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ComPentairPentairhome.Remove_ButtonInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.SaltAmount_Field'.", repo.ComPentairPentairhome.SaltAmount_FieldInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ComPentairPentairhome.SaltAmount_FieldInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ComPentairPentairhome.ADJUSTSALT_button'.", repo.ComPentairPentairhome.ADJUSTSALT_buttonInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ComPentairPentairhome.ADJUSTSALT_buttonInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.Date_Field'.", repo.ComPentairPentairhome.Date_FieldInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ComPentairPentairhome.Date_FieldInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
